spring.application.name=NoMoreLaps
app.jwt.secret=${APP_JWT_SECRET:CAMBIA_ESTE_SECRETO_MUY_LARGO_MIN_32_CHARS}
app.jwt.expiration-minutes=60
app.cors.allowed-origins=http://localhost:3000,http://localhost:4200
springdoc.swagger-ui.path=/swagger-ui.html

# Database Configuration (PostgreSQL)
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://db:5432/nomorelaps_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:nomorelaps_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:nomorelaps_pass}
spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.datasource.driver-class-name=org.postgresql.Driver
spring.jpa.show-sql=true

# Carga de datos gestionada por DataInitializer.java
spring.sql.init.mode=never

# Configuración para compatibilidad con Túneles y Swagger
server.forward-headers-strategy=framework
springdoc.api-docs.enabled=true
springdoc.swagger-ui.enabled=true
springdoc.writer-with-default-pretty-printer=true
springdoc.api-docs.groups.enabled=true

google.maps.api.key=${GOOGLE_MAPS_API_KEY:}
# Odoo ERP Integration
odoo.url=${ODOO_URL:http://nomorelaps-odoo:8069}
odoo.db=${ODOO_DB:nomorelaps}
odoo.username=${ODOO_USER:nomorelaps}
odoo.password=${ODOO_PASS:admin}
